project:
  type: website
  output-dir: docs

website:
  title: "Scott Flaska | Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/scottflaska
      - icon: twitter
        href: https://twitter.com/scottflaska
format:
  html:
    theme: solar
    css: styles.css

editor: visual

