---
title: "Predicting "
author: "Scott Flaska"
date: "2023-04-10"
draft: true
categories: [shotlink, golf, r]
image: ""
format: html
---

```{r}
#| output: false
library(tidyverse)
```

```{r}
shot_level <- readRDS("../02_shotlink_explore/shot_level.rds")

strokes_remaining <- shot_level %>% 
  group_by(player,
           hole,
           round) %>% 
  arrange(player,
          round,
          hole,
          shot) %>% 
  mutate(strokes_rolling = cumsum(num_of_strokes)) %>% 
  mutate(strokes_remaining_from_location = hole_score - strokes_rolling + 1,
         strokes_remaining_to_location = hole_score - strokes_rolling) %>%
  ungroup() %>% 
  mutate(yards_out_to_location = distance_to_hole_after_the_shot/36,
         yards_out_from_location = distance_to_pin/36) %>% 
  as.data.frame()

strokes_remaining %>% 
  filter(hole == 1,
         round == 1,
         player == 24924) %>% 
  select(shot,
         strokes_remaining_from_location,
         yards_out_from_location,
         strokes_remaining_to_location,
         yards_out_to_location)

strokes_remaining %>% 
  filter(!is.na(x)) %>% 
  filter(hole == 1,
         round == 1) %>% 
  mutate(strokes_remaining_to_location = factor(strokes_remaining_to_location,
                                                ordered = T)) %>%
  ggplot(mapping = aes(x = x,
                       y = y,
                       color = strokes_remaining_to_location)) +
  geom_point(size = 3) +
  coord_equal() +
  labs(title = "1st Hole") +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        panel.grid = element_blank(),
        legend.position = "bottom")

strokes_remaining %>% 
  filter(!is.na(x)) %>% 
  filter(hole == 1,
         round == 1) %>% 
  mutate(hole_score = factor(hole_score,
                             ordered = T)) %>%
  ggplot(mapping = aes(x = x,
                       y = y,
                       color = hole_score)) +
  geom_point(size = 3) +
  coord_equal() +
  labs(title = "1st Hole") +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        panel.grid = element_blank(),
        legend.position = "bottom")
```
